import React from 'react'
import Head from 'next/head'
import { MyEditor } from '@soosap/my-editor'
import { $getRoot } from 'lexical'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>MyEditor</div>
        <MyEditor
          name="ConfirmationAssistant"
          initialEditorState={(editor) => {
            const root = $getRoot()
            console.log('root', root)
            console.log('editor', editor)
          }}
        />
      </main>
    </>
  )
}
